// to get the user Repositories
export const GET_REPOSITORIES_REQUEST = "GET_REPOSITORIES_REQUEST"
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS"
export const GET_REPOSITORIES_FAILURE = "GET_REPOSITORIES_FAILURE"

// to get the followers list
export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST"
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS"
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE"

//to get individual repository
export const GET_REPO_REQUEST = "GET_REPO_REQUEST"
export const GET_REPO_SUCCESS = "GET_REPO_SUCCESS"
export const GET_REPO_FAILURE = "GET_REPO_FAILURE"