// to get the user Repositories
export const GET_REPOSITORIES_REQUEST = "GET_REPOSITORIES_REQUEST"
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS"
export const GET_REPOSITORIES_FAILURE = "GET_REPOSITORIES_FAILURE"

// to get the followers list
export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST"
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS"
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE"